# Generated by Django 6.0.7 on 2026-08-31 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sboms', '0011_ground_truth_classification_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPEAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=16)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('query_count', models.PositiveIntegerField()),
                ('candidate_family_count', models.PositiveIntegerField()),
                ('top1_accuracy', models.FloatField(blank=True, null=True)),
                ('recall_at_5', models.FloatField(blank=True, null=True)),
                ('recall_at_10', models.FloatField(blank=True, null=True)),
                ('mrr', models.FloatField(blank=True, null=True)),
                ('unique_correct_count', models.PositiveIntegerField(blank=True, null=True)),
                ('ambiguous_count', models.PositiveIntegerField(blank=True, null=True)),
                ('not_top_group_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['algorithm_id', 'status', '-created_at'], name='cpe_run_alg_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['RUNNING', 'COMPLETED', 'FAILED'])), name='cpe_analysis_run_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='CPEAnalysisQueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_score', models.FloatField()),
                ('better_count', models.PositiveIntegerField()),
                ('tie_size', models.PositiveIntegerField()),
                ('best_rank', models.PositiveIntegerField()),
                ('worst_rank', models.PositiveIntegerField()),
                ('outcome', models.CharField(choices=[('UNIQUE_CORRECT', 'Unique correct'), ('CORRECT_BUT_AMBIGUOUS', 'Correct but ambiguous'), ('NOT_TOP_GROUP', 'Not top group')], max_length=32)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpe_analysis_results', to='sboms.component')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_results', to='cpe_analysis.cpeanalysisrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'component'), name='unique_cpe_run_component'), models.CheckConstraint(condition=models.Q(('tie_size__gte', 1)), name='cpe_result_tie_size_gte_1'), models.CheckConstraint(condition=models.Q(('best_rank__gte', 1)), name='cpe_result_best_rank_gte_1'), models.CheckConstraint(condition=models.Q(('worst_rank__gte', 1)), name='cpe_result_worst_rank_gte_1'), models.CheckConstraint(condition=models.Q(('best_rank__lte', models.F('worst_rank'))), name='cpe_result_rank_order_valid'), models.CheckConstraint(condition=models.Q(models.Q(('best_rank', 1), ('outcome', 'UNIQUE_CORRECT'), ('worst_rank', 1)), models.Q(('best_rank', 1), ('outcome', 'CORRECT_BUT_AMBIGUOUS'), ('worst_rank__gt', 1)), models.Q(('best_rank__gt', 1), ('outcome', 'NOT_TOP_GROUP')), _connector='OR'), name='cpe_result_outcome_consistent')],
            },
        ),
    ]
