# Generated by Django 6.0.7 on 2026-07-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpeDictionarySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('IMPORTING', 'Importing'), ('COMPLETE', 'Complete')], max_length=16)),
                ('feed_last_modified', models.DateTimeField()),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('archive_sha256', models.CharField(max_length=64)),
                ('content_sha256', models.CharField(max_length=64)),
                ('member_count', models.PositiveIntegerField()),
                ('expected_record_count', models.BigIntegerField()),
                ('record_count', models.BigIntegerField()),
                ('active_count', models.BigIntegerField()),
                ('deprecated_count', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CpeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpe_name_id', models.UUIDField()),
                ('cpe_name', models.TextField()),
                ('deprecated', models.BooleanField()),
                ('created_at_nvd', models.DateTimeField()),
                ('last_modified_at_nvd', models.DateTimeField()),
                ('part', models.TextField()),
                ('vendor', models.TextField()),
                ('product', models.TextField()),
                ('version', models.TextField()),
                ('update', models.TextField()),
                ('edition', models.TextField()),
                ('language', models.TextField()),
                ('sw_edition', models.TextField()),
                ('target_sw', models.TextField()),
                ('target_hw', models.TextField()),
                ('other', models.TextField()),
                ('titles', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('deprecated_by', models.JSONField(default=list)),
                ('deprecates', models.JSONField(default=list)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpe_names', to='cpe_dictionary.cpedictionarysnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'deprecated'], name='cpe_snap_deprecated_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'cpe_name_id'), name='unique_cpe_id_per_snapshot'), models.UniqueConstraint(fields=('snapshot', 'cpe_name'), name='unique_cpe_name_per_snapshot')],
            },
        ),
    ]
