# Generated by Django 6.0.7 on 2026-07-25 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=128)),
                ('platform', models.CharField(default='linux/amd64', max_length=64)),
                ('manifest_digest', models.CharField(max_length=71, unique=True)),
                ('pinned_reference', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['repository', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='SBOMDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=512)),
                ('file_sha256', models.CharField(max_length=64, unique=True)),
                ('format', models.CharField(choices=[('CYCLONEDX_JSON', 'CycloneDX JSON')], default='CYCLONEDX_JSON', max_length=32)),
                ('spec_version', models.CharField(max_length=32)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('document_version', models.PositiveIntegerField(default=1)),
                ('generator_name', models.CharField(max_length=128)),
                ('generator_version', models.CharField(max_length=64)),
                ('source_type', models.CharField(default='registry', max_length=32)),
                ('scope', models.CharField(default='squashed', max_length=32)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('docker_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sbom_documents', to='sboms.dockerimage')),
            ],
            options={
                'ordering': ['docker_image__repository', 'docker_image__tag'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_ref', models.CharField(max_length=1024)),
                ('component_type', models.CharField(max_length=64)),
                ('group', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('purl', models.TextField(blank=True)),
                ('cpe', models.TextField(blank=True)),
                ('properties', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sbom_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='sboms.sbomdocument')),
            ],
            options={
                'ordering': ['name', 'version'],
            },
        ),
        migrations.AddConstraint(
            model_name='sbomdocument',
            constraint=models.UniqueConstraint(fields=('docker_image', 'generator_name', 'generator_version', 'format', 'file_sha256'), name='unique_sbom_document_import'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['sbom_document', 'name'], name='component_sbom_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('sbom_document', 'bom_ref'), name='unique_component_bom_ref_per_sbom'),
        ),
    ]
