# Generated by Django 6.0.7 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_dictionary", "0001_initial"),
        ("sboms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentCpeGroundTruth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(max_length=255),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cpe_ground_truths",
                        to="sboms.component",
                    ),
                ),
                (
                    "ground_truth_cpe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="component_ground_truths",
                        to="cpe_dictionary.cpename",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="component_ground_truths",
                        to="cpe_dictionary.cpedictionarysnapshot",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="componentcpegroundtruth",
            constraint=models.UniqueConstraint(
                fields=("component", "snapshot"),
                name="unique_component_ground_truth_per_snapshot",
            ),
        ),
    ]
