# Generated by Django 6.0.7 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0002_componentcpegroundtruth"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentcpegroundtruth",
            name="manual_ground_truth_cpe",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="componentcpegroundtruth",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(ground_truth_cpe__isnull=True)
                    | models.Q(manual_ground_truth_cpe="")
                ),
                name="ground_truth_has_one_cpe_source",
            ),
        ),
    ]
