# Generated by Django 6.0.7 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models
from django.db.models.functions import Lower


INITIAL_DECISION_TYPES = (
    (
        "Official CPE confirmed",
        (
            "The exact active CPE Name is present in the selected "
            "CPE Dictionary snapshot."
        ),
    ),
    (
        (
            "Official CPE family confirmed; version not in "
            "Dictionary"
        ),
        (
            "The canonical part, vendor, and product are confirmed, "
            "but the exact component version is absent from the "
            "selected CPE Dictionary snapshot."
        ),
    ),
    (
        "Distribution package revision normalized",
        (
            "A distribution-specific package revision was removed "
            "while preserving the confirmed upstream product "
            "version."
        ),
    ),
    (
        "Deprecated CPE redirected to active CPE",
        (
            "A deprecated CPE or alias was resolved to its active "
            "canonical CPE."
        ),
    ),
    (
        "Mapped to parent product CPE",
        (
            "The component is a subpackage or derived package "
            "represented by the parent product's CPE."
        ),
    ),
    (
        "No independent CPE",
        (
            "The component is a subpackage, data package, "
            "compatibility package, or internal unit without an "
            "independent CPE identity."
        ),
    ),
    (
        "Direct official CPE not confirmed",
        (
            "No directly corresponding official CPE family could "
            "be confirmed from the available evidence."
        ),
    ),
)


def reset_ground_truth_and_seed_taxonomy(apps, schema_editor):
    GroundTruth = apps.get_model("sboms", "ComponentCpeGroundTruth")
    DecisionType = apps.get_model("sboms", "GroundTruthDecisionType")
    database_alias = schema_editor.connection.alias

    GroundTruth.objects.using(database_alias).all().delete()

    for name, description in INITIAL_DECISION_TYPES:
        decision_type = (
            DecisionType.objects.using(database_alias)
            .filter(name__iexact=name)
            .first()
        )
        if decision_type is None:
            DecisionType.objects.using(database_alias).create(
                name=name,
                description=description,
                is_active=True,
            )
        else:
            decision_type.name = name
            decision_type.description = description
            decision_type.is_active = True
            decision_type.save(
                using=database_alias,
                update_fields=(
                    "name",
                    "description",
                    "is_active",
                    "updated_at",
                ),
            )


def remove_seed_taxonomy(apps, schema_editor):
    DecisionType = apps.get_model("sboms", "GroundTruthDecisionType")
    DecisionType.objects.using(
        schema_editor.connection.alias
    ).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0003_componentcpegroundtruth_manual_cpe"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroundTruthDecisionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
            ],
            options={"ordering": ("name", "id")},
        ),
        migrations.RunPython(
            reset_ground_truth_and_seed_taxonomy,
            remove_seed_taxonomy,
        ),
        migrations.RemoveField(
            model_name="componentcpegroundtruth",
            name="decision_type",
        ),
        migrations.AddField(
            model_name="componentcpegroundtruth",
            name="decision_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ground_truths",
                to="sboms.groundtruthdecisiontype",
            ),
        ),
        migrations.AlterField(
            model_name="componentcpegroundtruth",
            name="decision_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ground_truths",
                to="sboms.groundtruthdecisiontype",
            ),
        ),
        migrations.AddConstraint(
            model_name="groundtruthdecisiontype",
            constraint=models.UniqueConstraint(
                Lower("name"),
                name="unique_ground_truth_decision_type_name_ci",
            ),
        ),
    ]
