# Generated by Django 6.0.7 on 2026-08-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0005_resolution_outcome_correction_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbomdocument",
            name="manufacturer",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sbomdocument",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sbomdocument",
            name="product_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sbomdocument",
            name="product_version",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sbomdocument",
            name="docker_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sbom_documents",
                to="sboms.dockerimage",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="sbomdocument",
            name="unique_sbom_document_import",
        ),
        migrations.AlterModelOptions(
            name="sbomdocument",
            options={"ordering": ["-imported_at", "-id"]},
        ),
    ]
