# Generated by Django 6.0.7 on 2026-08-05

import sboms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0006_generalize_sbom_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbomdocument",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=sboms.models.sbom_uploaded_file_path,
            ),
        ),
    ]
