# Generated by Django 6.0.7 on 2026-08-18 02:15

import django.db.models.deletion
import sboms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sboms', '0009_version_mismatch_discrepancy_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_archive', models.FileField(max_length=255, upload_to=sboms.models.source_artifact_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sbom_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_artifact', to='sboms.sbomdocument')),
            ],
        ),
    ]
