# Generated by Django 6.0.7 on 2026-08-20 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NvdCveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('IMPORTING', 'Importing'), ('COMPLETE', 'Complete')], max_length=16)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('content_sha256', models.CharField(max_length=64)),
                ('feed_count', models.PositiveIntegerField()),
                ('record_count', models.BigIntegerField()),
                ('configuration_count', models.BigIntegerField()),
                ('cpe_match_count', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NvdCveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=32)),
                ('published_at_nvd', models.DateTimeField()),
                ('last_modified_at_nvd', models.DateTimeField()),
                ('vuln_status', models.TextField()),
                ('configurations', models.JSONField(null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cve_records', to='nvd_cve.nvdcvesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='NvdCpeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_index', models.PositiveIntegerField()),
                ('node_index', models.PositiveIntegerField()),
                ('match_index', models.PositiveIntegerField()),
                ('configuration_operator', models.TextField(null=True)),
                ('configuration_negate', models.BooleanField(null=True)),
                ('node_operator', models.TextField(null=True)),
                ('node_negate', models.BooleanField(null=True)),
                ('vulnerable', models.BooleanField()),
                ('criteria', models.TextField()),
                ('match_criteria_id', models.UUIDField()),
                ('version_start_including', models.TextField(null=True)),
                ('version_start_excluding', models.TextField(null=True)),
                ('version_end_including', models.TextField(null=True)),
                ('version_end_excluding', models.TextField(null=True)),
                ('cve_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpe_matches', to='nvd_cve.nvdcverecord')),
            ],
            options={
                'indexes': [models.Index(fields=['criteria'], name='nvd_match_criteria_idx'), models.Index(fields=['match_criteria_id'], name='nvd_match_id_idx'), models.Index(fields=['vulnerable'], name='nvd_match_vuln_idx')],
                'constraints': [models.UniqueConstraint(fields=('cve_record', 'configuration_index', 'node_index', 'match_index'), name='unique_nvd_cpe_match_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='nvdcverecord',
            constraint=models.UniqueConstraint(fields=('snapshot', 'cve_id'), name='unique_nvd_cve_per_snapshot'),
        ),
    ]
